name: Spring Boot CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Update based on your project
          distribution: 'adopt'
          cache: maven
      
      - name: set up enviroment variables
        run: echo "DATABASE_URL=jdbc:postgresql://localhost:5432/test_db" >> $GITHUB_ENV
        shell: bash
        
      # Step 3: Build with Maven
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          mkdir artifacts
          cp target/*.jar artifacts
          ls artifacts

      # Step 4: Save artifact
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-actions-artifact
          path: artifacts
